name: CI - Pull Request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  swiftlint:
    name: SwiftLint
    uses: ./.github/workflows/swiftlint.yml
    secrets: inherit
  test:
    name: Testing CodeEditTextView
    needs: swiftlint
    uses: ./.github/workflows/tests.yml
    secrets: inherit
