name: SwiftLint
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:
jobs:
  SwiftLint:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for SwiftLint with --strict
        run: swiftlint --strict
