name: tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:
jobs:
  code-edit-text-view-tests:
    name: Testing CodeEditTextView
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Testing Package
        run: exec ./.github/scripts/tests.sh arm
